### ISSUE TITLE
Things to do after merging beyond-networks

### ISSUE THREAD

**Issue by apozas** [ecboghiu/inflation#54]
As you may have seen, [the merge](https://github.com/ecboghiu/inflation/commit/dda764a6d474836a8725439254bd64b077948d84) has happened (do not confuse with [the merge](https://ethereum.org/en/upgrades/merge/) that the rest of the world is talking about, also expected to happen this week). It was not as traumatic as we expected, but that does not mean that all is done. There is still a bit of road ahead in terms of code formatting, presentation, documentation, and functionality.

# How to address the tasks
Now that the ``devel`` branch, **all commits must be done in that branch**, and not in ``main``.

Do not do partial commits, and commit modifications one at a time: this means that every commit must address *one* of the items below and *solve it completely*. This means we should actively work in avoiding commits like [this one](https://github.com/ecboghiu/inflation/commit/761d29bbd87f8014dcf28b0417085affcc178a7a), [this one](https://github.com/ecboghiu/inflation/commit/24809fac2bdb2422fae31eda84ee8c476f3a92ed) or [this one](https://github.com/ecboghiu/inflation/commit/ef11c89f33977550e1e9aeb1a2994c8acd99fe70). If one task requires several commits, the procedure should be
1. create a separate branch 
2. implement the changes in the branch
3. make pull request

The message of the commits should contain the text ``This fixes ..., listed in #54``, and after committing one should edit this issue by ticking the corresponding item and appending at the end of it the URL to the commit. See the ones already done as examples.

_Pro tip_: When doing commits, adding a paragraph break will separate the commit message in title and content, like [this one](https://github.com/ecboghiu/inflation/commit/346d16197911086c3c6e4c4105c9de8e6d9f305b).

# Tasks left
Note that this is not an extensive list: items may be added as we navigate through the code. But please do not delete items of the list.

## Tasks related to functionality
- [x] I did a clean install, and ``methodtools`` seems to be required. Thus, we shall add it to the list of required libraries. (done in https://github.com/ecboghiu/inflation/commit/5a118ef0229479847e09ddbb5b05de2557fabcc4)
- [x] Check whether the functions in [``writer_utils.py``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/writer_utils.py) work as expected, and fix if not. (https://github.com/ecboghiu/inflation/commit/34207a8490e20cc580c1f80195a50879a6635acd, https://github.com/ecboghiu/inflation/commit/9b7f25818a4fe3af8bd139626f78641f059b443a, https://github.com/ecboghiu/inflation/commit/2c2f783f2e76dead6858f8446730a4f899538b8d)
- [x] [``solveSDP_MosekFUSION``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/sdp_utils.py#L13) accepts as input and uses ``positive_vars``. This was [removed in ``main``](https://github.com/ecboghiu/inflation/commit/e0630bdbfc93fe6427922bfd562825c4a8e5cc8e) by making the appropriate changes in ``InflationSDP.moment_lowerbounds``. We must implement the analogous of this in the current code. (https://github.com/ecboghiu/inflation/commit/2c0a403adfd0b93f1e7f6637f4bf10c69361d120)
- [x] When running tests, I find several times the warning ``/causalinflation/quantum/fast_npa.py:269: RuntimeWarning: overflow encountered in ubyte_scalars``. We should find the reason of this and modify the code so that it does not appear. (https://github.com/ecboghiu/inflation/commit/652c64a7d93989576059997e47e2d3b026c7d5bf)
- [x] Testing ``test_lpi_bounds`` throws a ``UserWarning`` on ``verbose=0``. This should only appear for ``verbose > 0``, and in fact now what we have the ``Monomial`` class it would be nice to use another representation of the monomial so it is clearer to the user. (https://github.com/ecboghiu/inflation/commit/22178d7c2a2e809d775cf859aa5ac43028a92429)
- [x] In the current code, ``test_CHSH`` is failing. I left this on purpose. The error is triggered by using ``InflationSDP.set_values()`` using an integer to represent the monomial. I think that setting values using the integer representation of the monomial should be useful for the end user, but I am willing to hear opinions. (https://github.com/ecboghiu/inflation/commit/107b4550af829c6d0a96625cf9b7bb0201e9c5f6)
- [x] #56 (https://github.com/ecboghiu/inflation/commit/ba5485e9746469b51074b26a5a987e14375a8d69)
- [x] When running ``InflationSDP.generate_relaxation()`` with the flag ``InflationSDP.verbose`` set to ``> 0``, there is a printout saying ``Setting objective``. Since no objective is being set at this stage, this message must not appear (while appearing when actually setting an objective, if we want this to be the case, which @apozas is not completely convinced of). (https://github.com/ecboghiu/inflation/commit/2f30c965850582c9dbd2c72ffd18f1c797f9122d)
- [x] Create a `InflationSDP.set_bounds()` function (see #55).
- [x] I saw that [a recent commit](https://github.com/ecboghiu/inflation/commit/c3d08ea9ee73e0c48139f8cd2b02ed6bb7ed25e2) added the argument `consider_only_semiknowable` to `set_values`. What is the motivation for this? Is there any situation in which we can imagine wanting to fix the semiknowable moments but not the knowable ones? @eliewolfe. The decision was to remove the new parameters, see #68. (https://github.com/ecboghiu/inflation/commit/e4fb527c2fe02b8ecf6dd2b7bda94d6e82b33314, https://github.com/ecboghiu/inflation/commit/7152cd0e39dbd572d569721a7a30fe9cb9821c4b)
- [x] The file `fast_npa.py` now has the variables `cache` and `nopython` set from the beginning so there is no need to specify their values every time (this is a good thing), but [these lines of code](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/fast_npa.py#L36) suggest that one may want to set `nopython=False` even when numba is installed (so they want an acceleration. Otherwise [the previous exception](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/fast_npa.py#L19) handles the situation correctly). When would a situation like this happen? E: @apozas While developing it is useful to be able to disable numba globally, write the logic for a new function and then after its working correctly, then do the process of making it compatible with numba. Regarding the cache, once I had errors where the wrong function was being loaded (the old cached, and not the new modified) which made debugging tedious. For developing, I found it useful to have the option to disable caching globally. Whether these options should be made available to the user, I don't know.

## Tasks related to documentation
- [x] In several functions, some arguments miss documentation. This is the case of [``calculate_momentmatrix``](https://github.com/ecboghiu/inflation/blob/d05d0a031e349155f04045f31eb5cf1724b3ab40/causalinflation/quantum/fast_npa.py#L813), for example. The corresponding descriptions must be added. In fast_npa, many of the functions which now depend on `lexorder` and `notcomm` do not have those arguments documented.
- [x] In a similar spirit, documentation must be produced for the currently undocumented functions.
- [x] Modify the documentation files to show the functions that we want to show in the API reference.

## Tasks related to code presentation
- [x] All the comments that are not clarifications (like commented chunks of code) must be deleted from ``main``. (https://github.com/ecboghiu/inflation/commit/1c87acde3648a6c36dd2de0cf796457197961ba6, needs more)
- [x] Go through the codes looking for functions that are unused, and remove them (see but do not limit yourselves to #60).
- [x] Several files have some ``if __name__ == "__main__":`` blocks at the end. Do you agree with eliminating them from ``main``?
- [x] Modify the code files so they adhere to PEP8 as much as possible.
- [x] Organize the files: first, organize them by theme blocks (see, for instance, [``fast_npa.py``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/fast_npa.py#L221)), and then alphabetically within each block. Before the merge, ``main`` looked like this, but now we should go through all the files again because this order is very likely lost.
- [x] In the same spirit as the above, ``fast_npa.py`` was the file containing all the numba-ifiable functions and ``general_tools.py`` was left for the rest. We have to redistribute the functions so this is the case again.
- [x] The file equivalent to [`types.py`](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/types.py) was removed (due to being unused) in https://github.com/ecboghiu/inflation/commit/eff499d870dee3c0e616d6c18f4345f02f0f9e92. So far I have not found uses of the objects defined in `types.py`, so I want to delete it. Do you agree with this?
- [x] Some functions (such as [this one](https://github.com/ecboghiu/inflation/blob/d05d0a031e349155f04045f31eb5cf1724b3ab40/causalinflation/quantum/fast_npa.py#L759)) has code in Spanish. This is not permissible, and we must look all the codes to modify all appearances of this.
- [x] Right now there are two functions for applying source permutations, [``apply_source_perm_monomial``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/general_tools.py#L122) and [``apply_source_permplus_monomial``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/general_tools.py#L158). Given that what the first does is just calling the second with modified arguments, do we need both? Why can't we merge them into one? (https://github.com/ecboghiu/inflation/commit/7c422ab5975f6c02325b8fb44c9b686d0e3d19ef)
- [x] In a similar way to above, now there is, [``commuting``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/fast_npa.py#L300) and [``nb_commuting``](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/fast_npa.py#L525). Can we eliminate one of them? (https://github.com/ecboghiu/inflation/commit/871e66cd442412523dfb74888ae3cf3eeefc084d)
- [x] A new file, [``scrap.py``](), has appeared in the repository. I believe that this file is not intended to be in the final codebase. Am I right in that? Is there any issue with eliminating this file? (https://github.com/ecboghiu/inflation/commit/8bc4e9e250804ca9d95a55392f2c82599a36b69a)
- [x] We should use the convention where functions that the user should not use should start with an underscore '_', and functions which the user should REALLY not use with a double underscore, '__'. Examples would be anything outside the `Exposed to the user` method block: `AtomicMonomial`, `monomial_from_list_of_atomic`, `Monomial`, `inflation_aware_knowable_q`, `atomic_knowable_q`, `inflation_aware_to_ndarray_representative`, `from_2dndarray`, `to_2dndarray`, `update_physical_lowerbounds`, `cleanup_after_set_values`, `clear_known_values`. I would say that `sanitise_monomial` and `_dump_to_file` should be lifted to user-accessible. Related: #71.
- [x] Write a few more comments on `InflationProblem.py`. In particular, I am not sure about what we are doing between [L140](https://github.com/ecboghiu/inflation/blob/main/causalinflation/InflationProblem.py#L140) and L157. @eliewolfe, could you summarize it in one sentence, in the spirit of the comment in [L76](https://github.com/ecboghiu/inflation/blob/main/causalinflation/InflationProblem.py#L76) (that describes what is going on until L113), the comment in [L124](https://github.com/ecboghiu/inflation/blob/main/causalinflation/InflationProblem.py#L124) (that describes what is going on until L139) or the comment in [L159](https://github.com/ecboghiu/inflation/blob/main/causalinflation/InflationProblem.py#L159)? (https://github.com/ecboghiu/inflation/commit/be520991d9dc4765362a167ab9ca2d86bdd99f19, https://github.com/ecboghiu/inflation/commit/aa8e9ddfb2c5796ae6d0b539c24b489b03772c30)
- [x] What is the property `InflationProblem.split_node_model` for? I see that it is used in `InflationSDP` when defining `inflation_aware_knowable_q`, but @eliewolfe could you add a one-liner comment explaining what it represents and why it is needed? (https://github.com/ecboghiu/inflation/commit/be520991d9dc4765362a167ab9ca2d86bdd99f19)
- [x] In `InflationSDP.py` there is this commented line saying ["Used only for internal diagnostics"](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/InflationSDP.py#L424). What is the piece of code that is used for internal diagnostics? Can we eliminate it, at least from `main`? (https://github.com/ecboghiu/inflation/commit/a9014899bedf33a516efc70b6f6f581dc837eb0d)

## Tasks related to the paper
- [x] From the understanding that I got from reading `InflationProblem.py`, it seems to me that we support non-network scenarios where visible nodes can have parents and children, but not scenarios where latent nodes have parents and children. This is the case, right? If yes, we should make it explicit in the paper.
- [x] Add an example on non-networks.

## Other tasks
- [x] Now that ``beyond-networks`` has been merged (and this already had the changes previously implemented in ``atomic-complete`` or equivalent functionality), I think that it is time to delete these branches, but I wanted to ask you first. Can I delete them @ecboghiu @eliewolfe?
- [x] Create a new branch for further developments. First, this is good practice so when the repository is made public people can be sure that at every time the code in ``main`` will be working, publication-ready code. Connecting to this, I have noticed that right now there are a few ["note-to-self"-style comments](https://github.com/ecboghiu/inflation/blob/main/causalinflation/quantum/InflationSDP.py#L309) that, of course, must not be in the public-ready versions. The way to keep these is having them in the ``develop`` branch, and eliminating them from the public-ready ``main``.

Once all the items in these lists are checked out, we will be very close to going public :)
